# -*- coding: utf-8 -*-
"""Atividade agrícola

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XNqgzV6y55S43kM8THpMvwSQ4WoT3l5a
"""

import csv
import os

laranja = []
cana_de_acucar = []

def carregar_dados_csv():
    """Carrega dados do arquivo CSV principal ao iniciar a aplicação"""
    global laranja, cana_de_acucar
    
    arquivo_csv = 'dados-agricolas.csv'
    laranja.clear()
    cana_de_acucar.clear()
    
    if os.path.exists(arquivo_csv):
        try:
            with open(arquivo_csv, 'r', encoding='utf-8') as file:
                reader = csv.DictReader(file)
                for row in reader:
                    cultura = row['Cultura'].strip().lower()
                    area = float(row['Área (m²)'])
                    total_insumo = float(row['Total Insumo (KG)'])
                    tipo_insumo = row['Tipo Insumo'].strip().lower()
                    
                    if cultura == 'laranja':
                        laranja.append((area, total_insumo, tipo_insumo))
                    elif cultura == 'cana-de-açúcar':
                        cana_de_acucar.append((area, total_insumo, tipo_insumo))
            
            print(f"-> Dados carregados de {arquivo_csv}")
            print(f"-> {len(laranja)} registro(s) de laranja carregados")
            print(f"-> {len(cana_de_acucar)} registro(s) de cana-de-açúcar carregados")
        except Exception as e:
            print(f"-> Erro ao carregar {arquivo_csv}: {e}")
    else:
        print("-> Nenhum arquivo CSV encontrado. Um novo será criado ao salvar os dados.")

def inserir_dados_cultura(nome_cultura, area_calculo_func):
    """Insere dados para uma cultura específica."""
    area = area_calculo_func()

    insumos_validos = ['fertilizante', 'adubo', 'defensor']
    tipo_insumo = ""
    while tipo_insumo not in insumos_validos:
        tipo_insumo = input(f'-> Qual o tipo de insumo será usado? Insumos válidos: {insumos_validos}').strip().lower()
        if tipo_insumo not in insumos_validos:
            print(f'-> Insumo inválido! Escolha entre as opções: {insumos_validos}')

    qtd_insumo = float(input('-> Quantidade de insumo por metro (KG): '))
    qtd_sulcos = int(input('-> Quantos sulcos a área plantada possui? '))
    tam_sulcos = int(input('-> Qual o tamanho de cada sulco (m)? '))

    total_mts = qtd_sulcos * tam_sulcos
    total_insumo = total_mts * qtd_insumo

    return nome_cultura, (area, total_insumo, tipo_insumo)

def calcular_area_retangular():
    """Calcula a área de uma cultura plantada em área retangular."""
    comprimento = int(input('-> Comprimento (m): '))
    largura = int(input('-> Largura (m): '))
    return comprimento * largura

def calcular_area_quadrada():
    """Calcula a área de uma cultura plantada em área quadrada."""
    lado = int(input('-> Comprimento do lado da área quadrada (m): '))
    return lado * lado

def inserir_dados():
    print('\nEscolha a cultura:')
    print('[1] - Laranja (plantada em área retangular)')
    print('[2] - Cana-de-açúcar (plantada em área quadrada)')
    cultura = int(input('Digite o número da cultura: '))

    if cultura == 1:
        return inserir_dados_cultura("laranja", calcular_area_retangular)
    elif cultura == 2:
        return inserir_dados_cultura("cana", calcular_area_quadrada)
    else:
        print('Opção inválida!')
        return None, None

def mostra_dados(lista, nome_cultura):
    """Mostra dados de uma cultura específica."""
    print(f'\n--- Dados de {nome_cultura} ---')
    if not lista:
        print(f'-> Nenhum dado de {nome_cultura} foi inserido ainda.')
        return

    esc = input('Deseja mostrar todos os registros? (s/n): ').strip().lower()

    if esc == 's':
        for i, (area, total_insumo, tipo_insumo) in enumerate(lista):
            print(f'\nRegistro {i}')
            print('---------------------------')
            print(f'Área: {area} m²')
            print(f'Total de insumo: {total_insumo} KG')
            print(f'Tipo de insumo: {tipo_insumo}')
            print('---------------------------')
    else:
        alt = int(input(f'Qual registro deseja mostrar? De 0 a {len(lista)-1}: '))
        if 0 <= alt < len(lista):
            area, total_insumo, tipo_insumo = lista[alt]
            print(f'\nRegistro {alt}')
            print('---------------------------')
            print(f'Área: {area} m²')
            print(f'Total de insumo: {total_insumo} KG')
            print(f'Tipo de insumo: {tipo_insumo}')
            print('---------------------------')
        else:
            print('-> Registro inválido!')

def exportar_csv():
    """Exporta dados filtrados para arquivos separados"""
    print('\n[1] Exportar apenas laranja')
    print('[2] Exportar apenas cana-de-açúcar')
    print('[3] Exportar todas as culturas')
    opcao = int(input('Escolha uma opção: '))
    
    if opcao == 1:
        if not laranja:
            print('-> Não há dados de laranja para exportar.')
            return
        print('-> Todos os dados de laranja já estão no arquivo principal: dados-agricolas.csv')
        
    elif opcao == 2:
        if not cana_de_acucar:
            print('-> Não há dados de cana-de-açúcar para exportar.')
            return
        print('-> Todos os dados de cana-de-açúcar já estão no arquivo principal: dados-agricolas.csv')
        
    elif opcao == 3:
        print('-> Todos os dados já estão no arquivo principal: dados-agricolas.csv')
    else:
        print('-> Opção inválida!')

def atualizar_csv():
    """Atualiza o arquivo CSV principal com todos os dados"""
    with open('dados-agricolas.csv', 'w', newline='', encoding='utf-8') as arquivo:
        writer = csv.writer(arquivo)
        writer.writerow(['Cultura', 'Área (m²)', 'Total Insumo (KG)', 'Tipo Insumo'])
        for area, total_insumo, tipo_insumo in laranja:
            writer.writerow(['Laranja', area, total_insumo, tipo_insumo])
        for area, total_insumo, tipo_insumo in cana_de_acucar:
            writer.writerow(['Cana-de-açúcar', area, total_insumo, tipo_insumo])
    print("-> Arquivo CSV principal atualizado com sucesso!")

def get_valid_int(prompt):
    """Helper function to get a valid integer input."""
    while True:
        try:
            return int(input(prompt))
        except ValueError:
            print("-> Entrada inválida! Por favor, insira um número inteiro.")

print("""
    _    ____ ____   ___ _____ _____ ____ _   _ 
   / \  / ___|  _ \ / _ \_   _| ____/ ___| | | |
  / _ \| |  _| |_) | | | || | |  _|| |   | |_| |
 / ___ \ |_| |  _ <| |_| || | | |__| |___|  _  |
/_/   \_\____|_| \_\\___/ |_| |_____\____|_| |_|

    🌾 AgroTech Manager - Sistema de Gestão Agrícola 🌾
      
      ⠀⠀⠀⠀⢀⣠⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣦⣄⡀⠀⠀⠀⠀
      ⠀⠀⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⡀⠀⠀
      ⠀⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣄⠀
      ⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡄
      ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
      ⣿⣿⣿⣿⡿⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⢿⣿⣿⣿⣿
      ⣿⣿⣿⡿⠃🏡⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀       ⠘⢿⣿⣿⣿
      ⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀       ⠀⠀⠀⠈⢿⣿⣿
      ⣿⡿⠁⠀🌱⠀⠀⠀⠀⠀⠀⠀⠀         ⠀⠀⠀⠀🌱⠈⢿⣿
      ⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀       ⠀⠀⠀⠀⠘⣿
      
   Bem-vindo ao AgroTech Manager! 🍊
   
   Sistema integrado de gestão agrícola que combina tecnologia 
   e praticidade para otimizar o controle de suas culturas.
   
   Use o menu abaixo para gerenciar dados de plantio, calcular
   insumos e gerar relatórios estatísticos das suas culturas! 🌾
""")

print("Verificando arquivo CSV principal existente...")
carregar_dados_csv()

running = True

while running:
    print('\n' + '---'*10)
    print(' --- MENU ---')
    print('1 - Inserir dados')
    print('2 - Mostrar dados')
    print('3 - Atualizar dados')
    print('4 - Deletar dados')
    print('5 - Sair')
    print('---'*10)

    escolha = get_valid_int('Digite sua escolha: ')

    if escolha == 1:
        cultura, resultado = inserir_dados()
        if cultura == 'laranja' and resultado:
            laranja.append(resultado)
            print(f'-> Registro de laranja inserido com sucesso!')
            atualizar_csv()
        elif cultura == 'cana' and resultado:
            cana_de_acucar.append(resultado)
            print(f'-> Registro de cana-de-açúcar inserido com sucesso!')
            atualizar_csv()

    elif escolha == 2:
        print('\n[1] Laranja\n[2] Cana-de-açúcar')
        exibir = get_valid_int('Qual cultura deseja exibir? ')
        if exibir == 1:
            mostra_dados(laranja, 'laranja')
        elif exibir == 2:
            mostra_dados(cana_de_acucar, 'cana-de-açúcar')
        else:
            print('Opção inválida! Por favor, digite uma das opções acima')

    elif escolha == 3:
        print('\n[1] Laranja\n[2] Cana-de-açúcar')
        atualizar = get_valid_int('Qual cultura deseja atualizar? ')
        if atualizar == 1 and laranja:
            at = get_valid_int(f'Qual registro deseja atualizar? De 0 a {len(laranja)-1}: ')
            if 0 <= at < len(laranja):
                _, resultado = inserir_dados()
                laranja[at] = resultado
                print('-> Registro atualizado com sucesso!')
                atualizar_csv()
            else:
                print('-> Registro inválido!')
        elif atualizar == 2 and cana_de_acucar:
            at = get_valid_int(f'Qual registro deseja atualizar? De 0 a {len(cana_de_acucar)-1}: ')
            if 0 <= at < len(cana_de_acucar):
                _, resultado = inserir_dados()
                cana_de_acucar[at] = resultado
                print('-> Registro atualizado com sucesso!')
                atualizar_csv()
            else:
                print('-> Registro inválido!')
        else:
            print('-> Não há dados para atualizar.')

    elif escolha == 4:
        print('\n[1] Deletar registro específico de laranja')
        print('[2] Deletar registro específico de cana-de-açúcar')
        print('[3] Limpar todos os dados de laranja')
        print('[4] Limpar todos os dados de cana-de-açúcar')
        print('[5] Limpar todos os dados')
        deletar = get_valid_int('Qual opção deseja escolher? ')
        if deletar == 1:
            if laranja:
                del1 = get_valid_int(f'Qual registro deseja deletar? De 0 a {len(laranja)-1}: ')
                if 0 <= del1 < len(laranja):
                    laranja.pop(del1)
                    print('-> Registro deletado com sucesso!')
                    atualizar_csv()
                else:
                    print('-> Registro inválido!')
            else:
                print('-> Nenhum dado de laranja para deletar.')
        elif deletar == 2:
            if cana_de_acucar:
                del1 = get_valid_int(f'Qual registro deseja deletar? De 0 a {len(cana_de_acucar)-1}: ')
                if 0 <= del1 < len(cana_de_acucar):
                    cana_de_acucar.pop(del1)
                    print('-> Registro deletado com sucesso!')
                    atualizar_csv()
                else:
                    print('-> Registro inválido!')
            else:
                print('-> Nenhum dado de cana-de-açúcar para deletar.')
        elif deletar == 3:
            if not laranja:
                print('-> Não há dados de laranja para limpar.')
            else:
                confirmacao = input('Tem certeza que deseja apagar TODOS os dados de laranja? (s/n): ').strip().lower()
                if confirmacao == 's':
                    laranja.clear()
                    print('-> Todos os dados de laranja foram apagados!')
                    atualizar_csv()
                else:
                    print('-> Operação cancelada.')
        elif deletar == 4:
            if not cana_de_acucar:
                print('-> Não há dados de cana-de-açúcar para limpar.')
            else:
                confirmacao = input('Tem certeza que deseja apagar TODOS os dados de cana-de-açúcar? (s/n): ').strip().lower()
                if confirmacao == 's':
                    cana_de_acucar.clear()
                    print('-> Todos os dados de cana-de-açúcar foram apagados!')
                    atualizar_csv()
                else:
                    print('-> Operação cancelada.')
        elif deletar == 5:
            if not laranja and not cana_de_acucar:
                print('-> Não há dados para limpar.')
            else:
                confirmacao = input('Tem certeza que deseja apagar TODOS os dados (laranja e cana-de-açúcar)? (s/n): ').strip().lower()
                if confirmacao == 's':
                    laranja.clear()
                    cana_de_acucar.clear()
                    print('-> Todos os dados foram apagados!')
                    atualizar_csv()
                else:
                    print('-> Operação cancelada.')
        else:
            print('Opção inválida!')

    elif escolha == 5:
        print('Encerrando o programa. Obrigado por usar nossos serviços!')
        running = False

    else:
        print('Opção inválida! Digite um número de 1 a 5.')
